steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push

  # 3단계 => kubectl set image deployment/mybackend04-nestjs my-backend-sha256-1=asia.gcr.io/iconic-glass-358105/my-backend:버전
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/lookatme-backend
      - my-backend-sha256-1=asia.gcr.io/lookatme-server-362412/my-backend:0.39

    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
