# deploy with instance
version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    env_file:
      - ./.env.dev
    ports:
      - 3000:3000

  my-redis:
    image: redis:latest
    ports:
      - 6379:6379
